### ISSUE TITLE
Extreme clipping in rubrics point value field

### ISSUE THREAD

**Issue by NukeHavoc** [LafColITS/moodle-theme_stellar#36]
Rubrics are comprised of criterion, each of which have levels. These levels can be assigned points. Steller is heavily clipping the "point value" field so you can't see the value you've entered.

To recreate:

1. Create an assignment.
2. Set the grade method to rubric.
3. Submit the assignment.
4. Edit the assignment and choose "Advanced grading"
5. Click on "Define Rubric"
6. Try entering point values for a level.

![extreme-clipping-in-rubric-points-value-field](https://cloud.githubusercontent.com/assets/808825/4815315/e04fd9ea-5ed5-11e4-8cd1-fbee9f9a15fd.png)

**Comment by mackensen** [comment]
This should be fixed now; just need to test.
