### ISSUE TITLE
Rubric levels fields are clipped in Stellar when you have more than 4 levels for a criterion

### ISSUE THREAD

**Issue by NukeHavoc** [LafColITS/moodle-theme_stellar#37]
If you have more than four levels in a rubric criterion, the "add level" button becomes clipped and almost unusable.

To recreate:

1. Create an assignment.
2. Set the grade method to rubric.
3. Submit the assignment.
4. Edit the assignment and choose "Advanced grading"
5. Click on "Define Rubric"
6. Enter at least four levels to a rubric criterion. 
7. See the button get clipped.

![rubric-add-level-button-gets-clipped](https://cloud.githubusercontent.com/assets/808825/4815356/4ced03e8-5ed6-11e4-806a-019e2436a204.png)

**Comment by mackensen** [comment]
Resolved upstream.
