### ISSUE TITLE
Rubric definition area does not match the size of the description field above it.

### ISSUE THREAD

**Issue by NukeHavoc** [LafColITS/moodle-theme_stellar#38]
When creating a rubric, the rubric definition area isn't as wide as text description field above (though they both re-size down the same way on smaller screens). This reinforces the sense of the area being clipped (per #37 "Rubric levels fields are clipped in Stellar when you have more than 4 levels for a criterion").

First reported in #37, splitting off as a separate ticket per mackensen's request.

![iworld-rubric-doesnt-match-width-of-description-field](https://cloud.githubusercontent.com/assets/808825/4938708/4253f6b4-65cd-11e4-86e3-507da0bd5e28.png)

**Comment by mackensen** [comment]
Resolved upstream.
