### ISSUE TITLE
Left-margin missing on contact interface 

### ISSUE THREAD

**Issue by NukeHavoc** [LafColITS/moodle-theme_stellar#40]
If you are in Moodle messaging and looking at a particular message, two icons appear -- one for you, one for the sender. These icons are surrounded by a grey border, but the gray border has no left margin so it overlaps the constraining box. The effect looks a bit off (I'd expect it to look more like the "offline contacts" area just above it.

![odd-formatting-on-messaging-page](https://cloud.githubusercontent.com/assets/808825/4938826/65cc79ee-65ce-11e4-8cf1-3be8a1528dbf.png)

**Comment by mackensen** [comment]
This is resolved in the latest bootstrap update.
