### ISSUE TITLE
CSS conflict with the Filtered Course Block

### ISSUE THREAD

**Issue by Jabraben** [LafColITS/moodle-theme_stellar#53]
Running the latest version of the filtered course block (v2.8.1) on Moodle 2.8.9 with Stelllar v0.2.6. 
The collapse/expand arrow icons overlap the titles as seen in this screenshot:
![screen shot 2016-04-11 at 2 48 40 pm](https://cloud.githubusercontent.com/assets/16310215/14472806/eeec2be4-00c2-11e6-8c66-51b5a8593577.png)

**Comment by mackensen** [comment]
This should be fixed in the current beta.

**Comment by mackensen** [comment]
Never mind, it's fine for administrators but broken for teachers.

**Comment by mackensen** [comment]
This is blocked by https://github.com/CLAMP-IT/moodle-blocks_filtered_course_list/issues/41.
